### ISSUE TITLE
this is a novel

### ISSUE THREAD

**Issue by atspencermadsen** [danblondell/00-Novel#1]
my issue is this is a novel. i really like this, its funny. i feel like if it wasn't a novel, there was no real plot or dialogue, just this this character (dan's?) thoughts, i'd be really into this. i think it should also be in the first person, another way of removing device & artifice & just getting to the meat of it, the insights. i don't mean to say getting rid of paula or the train station, but rather staying in a kind of constant immediacy of insights & consistency of voice. i only care about what arvin is doing to the extent that it immediately pays off. i don't have patience for other people's interactions with each other, or setting for the sake of setting. i want it all to be filtered through arvin's thoughts.

example of my favorite parts, a.k.a. the parts that aren't plot or dialogue:
Arvin could see why terrorists blew up train stations. They have a point, he thought to himself.
could still hear himself like you can still taste an egg after eating an egg
Too long fingernails, not enough ambition. Too messy bedside table, not enough having friends.

**Comment by danblondell** [comment]
I'm kind of tempted to leave this issue open just to see if others pile on.

**Comment by danblondell** [comment]
Even thought technically it's a "resolved" issue because it's not going to not be a novel. What format do you have in mind? A series of aphorisms?

**Comment by atspencermadsen** [comment]
i think it can be a novel actually, like a more cohesive version of 'you can make anything sad' or your take on something like anything by jean phillipe toussaint. something first person much more reliant on thought/perspective, rather than plot/dialogue

**Comment by atspencermadsen** [comment]
the anthologist by nicholson baker with its tangents and relationship conflict

**Comment by danblondell** [comment]
I'll check those out. I'm certainly shooting for minimum viable plot. In a prior version of this, I tried a few chapters in first person but it required a level of introspection that the character isn't capable of.

**Comment by atspencermadsen** [comment]
sweet, looking forward to reading more

**Comment by danblondell** [comment]
Thanks! Can't wait to hear what you think as it progresses.
