### ISSUE TITLE
Intentional misspelling of 'contacks' in 1-Ice is not intentional enough

### ISSUE THREAD

**Issue by jonstieg** [danblondell/00-Novel#2]
I like 'ligely' and I like 'ice' but 'contacks' is how everyone pronounces it. No one sneaks that 't' in at the end. So instead of 'contacks' being an obvious indicator of an accent, it looks too much like a misspelling. I can't really picture how this woman sounds so I can't come up with an alternate spelling that better captures how she says it.

**Comment by danblondell** [comment]
What if I change it to "Do you wear contexts?"

**Comment by danblondell** [comment]
Reading this with a little distance I realize I like "contacks"
